name: bnd
channels:
  - conda-forge
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cachecontrol=0.14.1
  - cachecontrol-with-filecache=0.14.1
  - certifi=2024.8.30
  - cffi=1.17.1
  - cleo=2.2.1
  - colorama=0.4.6
  - crashtest=0.4.1
  - dulwich=0.21.7
  - filelock=3.16.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - jaraco.classes=3.4.0
  - keyring=24.3.1
  - libffi=3.4.2
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - more-itertools=10.5.0
  - msgpack-python=1.1.0
  - openssl=3.4.0
  - pexpect=4.9.0
  - pip=24.3.1
  - pkginfo=1.11.2
  - platformdirs=4.3.6
  - poetry=1.8.4
  - poetry-core=1.9.1
  - poetry-plugin-export=1.8.0
  - ptyprocess=0.7.0
  - pycparser=2.22
  - pyproject_hooks=1.2.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-build=1.2.2.post1
  - python-fastjsonschema=2.21.0
  - python-installer=0.7.0
  - python_abi=3.10
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - setuptools=75.6.0
  - shellingham=1.5.4
  - tk=8.6.13
  - tomlkit=0.13.2
  - trove-classifiers=2024.10.21.16
  - urllib3=2.2.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - attrs==24.2.0
      - ./dist/beneuro_data-0.1.0-py3-none-any.whl
      - black==24.8.0
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cuda-python==12.6.0
      - distlib==0.3.8
      - docker==7.1.0
      - docstring-parser==0.16
      - exceptiongroup==1.2.2
      - fasteners==0.19
      - h5py==3.11.0
      - hdmf==3.14.4
      - hdmf-zarr==0.9.0
      - identify==2.6.1
      - iniconfig==2.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mypy-extensions==1.0.0
      - ndx-pose==0.1.1
      - neo==0.13.3
      - neuroconv==0.6.3
      - nodeenv==1.9.1
      - numcodecs==0.13.0
      - numpy==1.26.4
      - packaging==24.1
      - pandas==2.2.2
      - parse==1.20.2
      - pathspec==0.12.1
      - pluggy==1.5.0
      - pre-commit==4.0.0
      - probeinterface==0.2.24
      - psutil==6.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pynwb==2.8.2
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - quantities==0.15.0
      - referencing==0.35.1
      - rich==13.8.1
      - rpds-py==0.20.0
      - ruamel-yaml==0.17.40
      - ruamel-yaml-clib==0.2.8
      - scipy==1.14.1
      - six==1.16.0
      - spikeinterface==0.101.0
      - threadpoolctl==3.5.0
      - tomli==2.0.1
      - tqdm==4.66.5
      - typer==0.9.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - virtualenv==20.26.6
      - zarr==2.17.2
