name: bnd-test
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - numpy
  - pandas
  - pydantic
  - pynwb
  - scipy
  - pytest
  - cuda-python
  - rich
  - typer
  - python-dotenv
  - pip:
      - -e ./
      - neuroconv==0.6.3
      - docker
      - ndx-pose
      - probeinterface
      - spikeinterface
      - ruamel-yaml
